name: bok minutes analytics

#on:
#  schedule:
#    # 실제 스케쥴 작업이 시작될 cron을 등록.
#    # 크론은 https://crontab.guru/ 여기서 확인
#    # 이 크론은 월-금 10시 (한국시간 오후 7시)에 실행됩니다.
#    - cron: "00 10 * * 1-5"

on:
  workflow_dispatch:  # 수동으로 실행하는 이벤트

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Run Main Scripts
      run: |
        start_minutes.sh
    - name: Send results
      run: |
        python src/bok_minutes_send_analytics.py ${{secrets.NVR_MAIL_PWD}}